Issue #1 - Agrego idea posible y codigo sin testear (faltaria refinar…
snoopconsulting/FrontEnd pull request #2
Opened 2019-08-16 14:05 UTC by enuelmorales-snoop

…lo un poco mas)

2019-08-16 18:42 UTC, nfvelazco requested changes
Para que no se pierda en archivos md iria al js

2019-08-16 18:42 UTC, nfvelazco commented on notas.md
> +* Defino reglas y pseudo codigo para plantear la idea y luego llevarla a node.js
Enu pasa de notas al js todo lo que no sea codigo como comentarios.

2019-08-20 15:06 UTC, enuelmorales-snoop commented on notas.md
> +* Defino reglas y pseudo codigo para plantear la idea y luego llevarla a node.js
Dale en un rato lo arreglo

2019-08-20 16:44 UTC, nfvelazco approved these changes

2019-08-20 16:45 UTC, merged